spring:
    datasource:
    url: jdbc:mysql://localhost:3306/stg_dev
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
     ddl-auto: validate 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true